USE PCEPI2
GO


CREATE PROCEDURE RELACION_PL
(
@ID_LEMA int,
@ID_PERIODO int
)
AS INSERT INTO LEMA_PERIODO(ID_LEMA,ID_PERIODO) VALUES (@ID_LEMA,@ID_PERIODO)


ALTER PROCEDURE RELACION_LP
(
@titulo char(40),
@descripcion varchar(2100),
@ID_PERIODO int
)
AS 
BEGIN TRAN t1;
IF(@titulo IS NULL OR @descripcion IS NULL OR @ID_PERIODO IS NULL)
	BEGIN
		PRINT N'VARIABLES NULAS';
	END   
ELSE
	BEGIN	
		INSERT INTO Lema(titulo,descripcion) values(@titulo,@descripcion)
		declare @IDL int;
		SELECT @IDL=MAX(ID_LEMA) from LEMA where TITULO=@titulo and descripcion=@descripcion;
		INSERT INTO LEMA_PERIODO(ID_LEMA,ID_PERIODO) VALUES (@IDL,@ID_PERIODO)
	END
COMMIT TRAN t1;
GO
           
