USE PCEPI2
GO



create procedure AltasProyectos
(
@GRUPO char (4),
@INTERAREA bit,
@INTERPLANTEL bit,
@PROFESOR_ASIGNATURA bit,
@OFICIO char(4),
@FECHA_EVALUACION smalldatetime,
@TITULO varchar(400),
@PRODUCTO varchar(250),
@ID_CAMPO int,
@ID_MATERIA char(4),
@DESCRIPCION varchar(2500),
@ID_OPINION_DIRECTOR int,
@OBSERVACIONES nvarchar(500),
@IP_USUARIO char(15),
@ID_USUARIO uniqueidentifier,
@FECHA_REGISTRO smalldatetime,
@FIRMA bit	
)
as
	insert into PROYECTO_GRUPO1(GRUPO,INTERAREA,INTERPLANTEL,PROFESOR_ASIGNATURA,OFICIO,
	FECHA_EVALUACION,TITULO,PRODUCTO, ID_CAMPO,ID_MATERIA,DESCRIPCION,ID_OPINION_DIRECTOR,OBSERVACIONES,IP_USUARIO,
	ID_USUARIO,FECHA_REGISTRO,FIRMA) values (@GRUPO,@INTERAREA,@INTERPLANTEL,@PROFESOR_ASIGNATURA,@OFICIO,
	@FECHA_EVALUACION,@TITULO,@PRODUCTO, @ID_CAMPO,@ID_MATERIA,@DESCRIPCION,@ID_OPINION_DIRECTOR,@OBSERVACIONES,@IP_USUARIO,
	@ID_USUARIO,@FECHA_REGISTRO,@FIRMA)
	
	
	create procedure BorrarProyecto
	(
	@ID_PROYECTO_GRUPO int
	)
	as
		delete PROYECTO_GRUPO1 where  ID_PROYECTO_GRUPO=@ID_PROYECTO_GRUPO
	
	create procedure ObtenerProyecto
	as
	select GRUPO,INTERAREA,INTERPLANTEL,PROFESOR_ASIGNATURA,OFICIO,
	FECHA_EVALUACION,TITULO,PRODUCTO, ID_CAMPO,ID_MATERIA,DESCRIPCION,ID_OPINION_DIRECTOR,OBSERVACIONES,IP_USUARIO,
	ID_USUARIO,FECHA_REGISTRO,FIRMA from PROYECTO_GRUPO1
	
	create Procedure ObtenerProyectoByyID
	(
	@ID_PROYECTO_GRUPO int
	)	
	as
		select GRUPO,INTERAREA,INTERPLANTEL,PROFESOR_ASIGNATURA,OFICIO,
	FECHA_EVALUACION,TITULO,PRODUCTO, ID_CAMPO,ID_MATERIA,DESCRIPCION,ID_OPINION_DIRECTOR,OBSERVACIONES,IP_USUARIO,
	ID_USUARIO,FECHA_REGISTRO,FIRMA from PROYECTO_GRUPO1 where ID_PROYECTO_GRUPO=@ID_PROYECTO_GRUPO
	
	
	create procedure ActualizarProyecto
	(
	@ID_PROYECTO_GRUPO int,
	@GRUPO char (4),
@INTERAREA bit,
@INTERPLANTEL bit,
@PROFESOR_ASIGNATURA bit,
@OFICIO char(4),
@FECHA_EVALUACION smalldatetime,
@TITULO varchar(400),
@PRODUCTO varchar(250),
@ID_CAMPO int,
@ID_MATERIA char(4),
@DESCRIPCION varchar(2500),
@ID_OPINION_DIRECTOR int,
@OBSERVACIONES nvarchar(500),
@IP_USUARIO char(15),
@ID_USUARIO uniqueidentifier,
@FECHA_REGISTRO smalldatetime,
@FIRMA bit	

	)
	as
	update PROYECTO_GRUPO1 set   GRUPO=@GRUPO,INTERAREA=@INTERAREA,INTERPLANTEL=@INTERPLANTEL,PROFESOR_ASIGNATURA=@PROFESOR_ASIGNATURA,OFICIO =@OFICIO,
	FECHA_EVALUACION=@FECHA_EVALUACION,TITULO=@TITULO,PRODUCTO=@PRODUCTO, ID_CAMPO=@ID_CAMPO,ID_MATERIA=@ID_MATERIA,DESCRIPCION=@DESCRIPCION,ID_OPINION_DIRECTOR=@ID_OPINION_DIRECTOR,OBSERVACIONES=@OBSERVACIONES,IP_USUARIO=@IP_USUARIO,
	ID_USUARIO=@ID_USUARIO,FECHA_REGISTRO=@FECHA_REGISTRO,FIRMA=@FIRMA where ID_PROYECTO_GRUPO=@ID_PROYECTO_GRUPO
	
	