USE PCEPI2
GO

create procedure AltaFirmante1
(
@ID_PLANTEL smallint,
@ID_AREA smallint,
@RFC_PEC nvarchar(13),
@RFC_CONSEJERO1 nvarchar(13),
@RFC_CONSEJERO2 nvarchar(13),
@RFC_CONSEJERO3 nvarchar(13),
@RFC_CONSEJERO4 nvarchar(13),
@RFC_CONSEJERO5 nvarchar(13),
@RFC_CONSEJERO6 nvarchar(13),
@SIGLAS nchar(10),
@FECHA_OFICIO smalldatetime,
@ID_PERIODO smallint

)
as 
insert into FIRMANTE1(ID_PLANTEL,ID_AREA,RFC_PEC,RFC_CONSEJERO1,RFC_CONSEJERO1,RFC_CONSEJERO3,RFC_CONSEJERO4,RFC_CONSEJERO5,
RFC_CONSEJERO6,SIGLAS,FECHA_OFICIO,ID_PERIODO) values(@ID_PLANTEL,@ID_AREA,@RFC_PEC,@RFC_CONSEJERO1,@RFC_CONSEJERO1,@RFC_CONSEJERO3,@RFC_CONSEJERO4,@RFC_CONSEJERO5,
@RFC_CONSEJERO6,@SIGLAS,@FECHA_OFICIO,@ID_PERIODO)
Go



CREATE procedure BorrarFirmante1
(
@ID_FIRMANTE1 smallint
)
as delete FIRMANTE1 where ID_FIRMANTE1=@ID_FIRMANTE1


CREATE procedure ObtenerFirmante1
as select ID_FIRMANTE1,ID_PLANTEL,ID_AREA,RFC_PEC,RFC_CONSEJERO1,RFC_CONSEJERO1,RFC_CONSEJERO3,RFC_CONSEJERO4,RFC_CONSEJERO5,
RFC_CONSEJERO6,SIGLAS,FECHA_OFICIO,ID_PERIODO from FIRMANTE1




 
