USE PCEPI2
GO



create procedure AltasFIRMANTES1
(
	@ID_PLANTEL smallint,
	@ID_AREA smallint,
	@RFC_PEC nchar(13),
	@RFC_CONSEJERO1 nvarchar(13),
	@RFC_CONSEJERO2 nvarchar(13),
	@RFC_CONSEJERO3 nvarchar(13),
	@RFC_CONSEJERO4 nvarchar(13),
	@RFC_CONSEJERO5 nvarchar(13),
	@RFC_CONSEJERO6 nvarchar(13),
	@SIGLAS nchar(7),
	@FECHA_OFICIO smalldatetime,
	@ID_PERIODO smallint
)
as
	insert into FIRMANTE1(ID_PLANTEL,ID_AREA,RFC_PEC,RFC_CONSEJERO1,RFC_CONSEJERO2,RFC_CONSEJERO3,RFC_CONSEJERO4,
	RFC_CONSEJERO5,RFC_CONSEJERO6,SIGLAS,FECHA_OFICIO,ID_PERIODO) values (@ID_PLANTEL,@ID_AREA,@RFC_PEC,@RFC_CONSEJERO1,@RFC_CONSEJERO2,@RFC_CONSEJERO3,@RFC_CONSEJERO4,
	@RFC_CONSEJERO5,@RFC_CONSEJERO6,@SIGLAS,@FECHA_OFICIO,@ID_PERIODO)
	
	
	create procedure BorrarFIRMANTE1
	(
	@ID_FIRMANTE1 smallint
	)
	as
		delete FIRMANTES1 where  ID_FIRMANTE1=@ID_FIRMANTE1
	
	create procedure ObtenerFIRMANTE1
	as
	select ID_FIRMANTE1, ID_PLANTEL,ID_AREA,RFC_PEC,RFC_CONSEJERO1,RFC_CONSEJERO2,RFC_CONSEJERO3,RFC_CONSEJERO4,
	RFC_CONSEJERO5,RFC_CONSEJERO6,SIGLAS,FECHA_OFICIO,ID_PERIODO from FIRMANTE1
	
	create Procedure ObtenerFIRMANTE1ByyID
	(
	@ID_FIRMANTE1 smallint
	)	
	as
		select ID_FIRMANTE1, ID_PLANTEL,ID_AREA,RFC_PEC,RFC_CONSEJERO1,RFC_CONSEJERO2,RFC_CONSEJERO3,RFC_CONSEJERO4,
	RFC_CONSEJERO5,RFC_CONSEJERO6,SIGLAS,FECHA_OFICIO,ID_PERIODO from FIRMANTE1 where ID_FIRMANTE1=@ID_FIRMANTE1
	
	
	create procedure ActualizarFIRMANTE1
	(
	@ID_FIRMANTE1 int,
	@ID_PLANTEL smallint,
	@ID_AREA smallint,
	@RFC_PEC nchar(13),
	@RFC_CONSEJERO1 nvarchar(13),
	@RFC_CONSEJERO2 nvarchar(13),
	@RFC_CONSEJERO3 nvarchar(13),
	@RFC_CONSEJERO4 nvarchar(13),
	@RFC_CONSEJERO5 nvarchar(13),
	@RFC_CONSEJERO6 nvarchar(13),
	@SIGLAS nchar(7),
	@FECHA_OFICIO smalldatetime,
	@ID_PERIODO smallint
	)
	as
	update FIRMANTE1 set  ID_PLANTEL=@ID_PLANTEL,ID_AREA=@ID_AREA,RFC_PEC=@RFC_PEC,RFC_CONSEJERO1=@RFC_CONSEJERO1,RFC_CONSEJERO2=@RFC_CONSEJERO2,RFC_CONSEJERO3=@RFC_CONSEJERO3,RFC_CONSEJERO4=@RFC_CONSEJERO4,
	RFC_CONSEJERO5=@RFC_CONSEJERO5,RFC_CONSEJERO6=@RFC_CONSEJERO6,SIGLAS=@SIGLAS,FECHA_OFICIO=@FECHA_OFICIO,ID_PERIODO=@ID_PERIODO where ID_FIRMANTE1=@ID_FIRMANTE1
	
	