USE PCEPI2
GO



alter procedure AltaFIRMANTE1
(
	
	@RFC_PEC nchar(13),
	@RFC_CONSEJERO1 nvarchar(13),
	@RFC_CONSEJERO2 nvarchar(13),
	@RFC_CONSEJERO3 nvarchar(13),
	@RFC_CONSEJERO4 nvarchar(13),
	@RFC_CONSEJERO5 nvarchar(13),
	@RFC_CONSEJERO6 nvarchar(13),
	@SIGLAS nchar(7),
	@FECHA_OFICIO smalldatetime

)
as
	insert into FIRMANTE1(RFC_PEC,RFC_CONSEJERO1,RFC_CONSEJERO2,RFC_CONSEJERO3,RFC_CONSEJERO4,
	RFC_CONSEJERO5,RFC_CONSEJERO6,SIGLAS,FECHA_OFICIO) values (@RFC_PEC,@RFC_CONSEJERO1,@RFC_CONSEJERO2,@RFC_CONSEJERO3,@RFC_CONSEJERO4,
	@RFC_CONSEJERO5,@RFC_CONSEJERO6,@SIGLAS,@FECHA_OFICIO)
	
	
	alter procedure BorrarFIRMANTE1
	(
	@ID_FIRMANTE1 smallint
	)
	as
		delete FIRMANTES1 where  ID_FIRMANTE1=@ID_FIRMANTE1
	
	alter procedure ObtenerFIRMANTE1
	as
	select ID_FIRMANTE1,RFC_PEC,RFC_CONSEJERO1,RFC_CONSEJERO2,RFC_CONSEJERO3,RFC_CONSEJERO4,
	RFC_CONSEJERO5,RFC_CONSEJERO6,SIGLAS,FECHA_OFICIO from FIRMANTE1
	
	create Procedure ObtenerFIRMANTE1ByyID
	(
	@ID_FIRMANTE1 smallint
	)	
	as
		select ID_FIRMANTE1, RFC_PEC,RFC_CONSEJERO1,RFC_CONSEJERO2,RFC_CONSEJERO3,RFC_CONSEJERO4,
	RFC_CONSEJERO5,RFC_CONSEJERO6,SIGLAS,FECHA_OFICIO from FIRMANTE1 where ID_FIRMANTE1=@ID_FIRMANTE1
	
	
	create procedure ActualizarFIRMANTE1
	(
	@ID_FIRMANTE1 int,
	@RFC_PEC nchar(13),
	@RFC_CONSEJERO1 nvarchar(13),
	@RFC_CONSEJERO2 nvarchar(13),
	@RFC_CONSEJERO3 nvarchar(13),
	@RFC_CONSEJERO4 nvarchar(13),
	@RFC_CONSEJERO5 nvarchar(13),
	@RFC_CONSEJERO6 nvarchar(13),
	@SIGLAS nchar(7),
	@FECHA_OFICIO smalldatetime
	)
	as
	update FIRMANTE1 set  RFC_PEC=@RFC_PEC,RFC_CONSEJERO1=@RFC_CONSEJERO1,RFC_CONSEJERO2=@RFC_CONSEJERO2,RFC_CONSEJERO3=@RFC_CONSEJERO3,RFC_CONSEJERO4=@RFC_CONSEJERO4,
	RFC_CONSEJERO5=@RFC_CONSEJERO5,RFC_CONSEJERO6=@RFC_CONSEJERO6,SIGLAS=@SIGLAS,FECHA_OFICIO=@FECHA_OFICIO where ID_FIRMANTE1=@ID_FIRMANTE1
	
	