USE PCEPI2
GO

CREATE PROCEDURE ObtenerPeriodoByNombre
(
@NOMBRE_PERIODO char(9)
)
as select ID_PERIODO,NOMBRE_PERIODO,FECHA_INICIO,FECHA_TERMINO from PCEPI2 where NOMBRE_PERIODO=@NOMBRE_PERIODO

CREATE procedure ActualizarPeriodo
(
@ID_PERIODO smallint,
@NOMBRE_PERIODO varchar(9),
@FECHA_INICIO smalldatetime,
@FECHA_TERMINO smalldatetime
)
as 
 update PERIODO set NOMBRE_PERIODO=@NOMBRE_PERIODO,FECHA_INICIO=@FECHA_INICIO, FECHA_TERMINO=@FECHA_TERMINO where ID_PERIODO=@ID_PERIODO
 
CREATE procedure BorrarPeriodo
(
@ID_PERIODO smallint
)
as delete PERIODO where ID_PERIODO=@ID_PERIODO

CREATE procedure ObtenerPeriodos
as select ID_PERIODO,NOMBRE_PERIODO,FECHA_INICIO, FECHA_TERMINO from PERIODO




 
