USE PCEPI2
GO

create procedure AltaPeriodo
(
@NOMBRE_PERIODO varchar(20),
@FECHA_INICIO smalldatetime,
@FECHA_TERMINO smalldatetime
)
as 
insert into Periodo(NOMBRE_PERIODO,FECHA_INICIO,FECHA_TERMINO) values(@NOMBRE_PERIODO,@FECHA_INICIO,@FECHA_TERMINO)
Go

alter PROCEDURE ObtenerPeriodoByNombre
(
@NOMBRE_PERIODO char(20)
)
as select ID_PERIODO,NOMBRE_PERIODO,FECHA_INICIO,FECHA_TERMINO from PCEPI2 where NOMBRE_PERIODO=@NOMBRE_PERIODO

ALTER procedure ActualizarPeriodo
(
@ID_PERIODO int,
@NOMBRE_PERIODO varchar(20),
@FECHA_INICIO smalldatetime,
@FECHA_TERMINO smalldatetime
)
as 
 update PERIODO set NOMBRE_PERIODO=@NOMBRE_PERIODO,FECHA_INICIO=@FECHA_INICIO, FECHA_TERMINO=@FECHA_TERMINO where ID_PERIODO=@ID_PERIODO
 
CREATE procedure BorrarPeriodo
(
@ID_PERIODO int
)
as delete PERIODO where ID_PERIODO=@ID_PERIODO

CREATE procedure ObtenerPeriodos
as select ID_PERIODO,NOMBRE_PERIODO,FECHA_INICIO, FECHA_TERMINO from PERIODO




 
