USE [PCEPI2]
GO

/****** Object:  Table [dbo].[PROYECTO]    Script Date: 11/18/2015 21:03:16 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROYECTO]') AND type in (N'U'))
DROP TABLE [dbo].[PROYECTO]
GO

USE [PCEPI2]
GO

/****** Object:  Table [dbo].[PROYECTO]    Script Date: 11/18/2015 21:03:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PROYECTO](
	[ID_PROYECTO] [int] IDENTITY(1,1) NOT NULL,
	[PLANTEL] [varchar](20) NULL,
	[PERIODO] [varchar](20) NULL,
	[ID_AREA] [int] NULL,
	[NUM_OFICIO] [varchar](25) NULL,
	[FECHA_EVAL] [smalldatetime] NULL,
	[TITULO] [varchar](100) NULL,
	[PRODUCTO] [varchar](100) NULL,
	[CAMPO] [varchar](100) NULL,
	[DESCRIPCION_PROY] [varchar](1000) NULL,
	[OPINION_DIR] [varchar](20) NULL,
	[OBSERVACIONES] [varchar](500) NULL,
 CONSTRAINT [PK_PROYECTO] PRIMARY KEY CLUSTERED 
(
	[ID_PROYECTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PROYECTO_MP_PROYECTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[PROYECTO_MP]'))
ALTER TABLE [dbo].[PROYECTO_MP] DROP CONSTRAINT [FK_PROYECTO_MP_PROYECTO]
GO

USE [PCEPI2]
GO

/****** Object:  Table [dbo].[PROYECTO_MP]    Script Date: 11/18/2015 21:03:50 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROYECTO_MP]') AND type in (N'U'))
DROP TABLE [dbo].[PROYECTO_MP]
GO

USE [PCEPI2]
GO

/****** Object:  Table [dbo].[PROYECTO_MP]    Script Date: 11/18/2015 21:03:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PROYECTO_MP](
	[ID_PROYECTO_MP] [int] IDENTITY(1,1) NOT NULL,
	[ID_MATERIA] [char](4) NULL,
	[RFC] [char](13) NULL,
	[ID_PROYECTO] [int] NULL,
 CONSTRAINT [PK_PROYECTO_MP] PRIMARY KEY CLUSTERED 
(
	[ID_PROYECTO_MP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[PROYECTO_MP]  WITH CHECK ADD  CONSTRAINT [FK_PROYECTO_MP_PROYECTO] FOREIGN KEY([ID_PROYECTO])
REFERENCES [dbo].[PROYECTO] ([ID_PROYECTO])
GO

ALTER TABLE [dbo].[PROYECTO_MP] CHECK CONSTRAINT [FK_PROYECTO_MP_PROYECTO]
GO