USE [PCEPI2]
GO

/****** Object:  Table [dbo].[AREA]    Script Date: 12/21/2015 13:01:24 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AREA]') AND type in (N'U'))
DROP TABLE [dbo].[AREA]
GO

USE [PCEPI2]
GO

/****** Object:  Table [dbo].[AREA]    Script Date: 12/21/2015 13:01:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING OFF
GO

CREATE TABLE [dbo].[AREA](
	[ID_AREA] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_CORTO] [char](30) NOT NULL,
	[NOMBRE_LARGO] [char](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_AREA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [idarea] UNIQUE NONCLUSTERED 
(
	[ID_AREA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


