USE [PCEPI2]
GO

/****** Object:  Table [dbo].[PERIODO]    Script Date: 12/21/2015 13:28:46 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PERIODO]') AND type in (N'U'))
DROP TABLE [dbo].[PERIODO]
GO

USE [PCEPI2]
GO

/****** Object:  Table [dbo].[PERIODO]    Script Date: 12/21/2015 13:28:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PERIODO](
	[ID_PERIODO] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_PERIODO] [char](20) NOT NULL,
	[FECHA_INICIO] [smalldatetime] NOT NULL,
	[FECHA_TERMINO] [smalldatetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_PERIODO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


