USE [PCEPI2]
GO

/****** Object:  Table [dbo].[PLANTEL]    Script Date: 12/21/2015 13:29:50 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PLANTEL]') AND type in (N'U'))
DROP TABLE [dbo].[PLANTEL]
GO

USE [PCEPI2]
GO

/****** Object:  Table [dbo].[PLANTEL]    Script Date: 12/21/2015 13:29:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING OFF
GO

CREATE TABLE [dbo].[PLANTEL](
	[ID_PLANTEL] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [char](20) NOT NULL,
	[CVE_DEPENDENCIA] [char](5) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_PLANTEL] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


